name: CI Build
on:
  push:
    branches: [ master ]
  pull_request:
  schedule:
    - cron: "0 3 * * *" #nightly builds at 3am

jobs:
  build-linux:
    runs-on: linux-x64
    steps:
      - name: Check out source
        uses: actions/checkout@v3

#      - name: Install dependencies
#        run: |
#          sudo apt-get update
#          sudo apt-get install -y build-essential cmake

      - name: Configure
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cd build
          make -j$(nproc)

      - name: Upload build logs
        uses: actions/upload-artifact@v3
        with:
          name: build-logs
          path: build
